import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PathTracker } from '@/features/path-tracker/path-tracker';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: LayoutProps<'/'>) {
  const { children } = props;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#0a0b0d] bg-custom-gradient`}
    >
      <body>
        <main className="container mx-auto my-4 ">
          <div className="max-w-4xl bg-[#131519] rounded-2xl border border-[#23262b]">
            <div className="flex items-center gap-2.5 px-3.5 py-4 bg-[#0e1013] border-b-[#23262b] border-b rounded-t-2xl">
              <div className="w-2.5 h-2.5 rounded-full bg-[#e85d5d]"></div>
              <div className="w-2.5 h-2.5 rounded-full bg-[#e8b04f]"></div>
              <div className="w-2.5 h-2.5 rounded-full bg-[#7ee787]"></div>
              <PathTracker />
            </div>
            <div className="p-8">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
